# Generated by Django 5.0 on 2024-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='time_category',
            field=models.CharField(choices=[('BREAKFEST', 'breakfast'), ('LUNCH', 'lunsh'), ('DINNER', 'dinner'), ('dessert', 'desert'), ('Drinks', 'drinks'), ('Snacks', 'snacks')], max_length=50),
        ),
    ]
