# Generated by Django 5.0 on 2024-11-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_dish_time_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Menu',
        ),
    ]
