# Generated by Django 5.0 on 2024-11-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_dish_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name_dish',
            new_name='name',
        ),
    ]
