# Generated by Django 5.0 on 2024-11-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_name_dish_menu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='time_category',
            new_name='category',
        ),
    ]
