# Generated by Django 5.0 on 2024-11-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_menu_prf_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('vip', 'vip'), ('table', 'table'), ('Cud', 'cud')], max_length=50),
        ),
    ]
